publish = "publish.yaml"
language="en"

[[input]]
name = "SCHED"
dir = "Personal Scheduler App"
driver = "obsidian"
atype = "SRS"
marker = "REQ"
markers = ["COM", "DES", "TABLE", "FIG"]

[drivers.obsidian]
integration = true
strict_line_breaks = "auto"
exclude_elements = [
  {name = "tags", mode = "string-on-start"},
]

[metrics]
enabled = true
requirement_type = "REQ"
status_field = "status"
verify_field = "verify"
tbd_marker = "TBD"

[impact]
enabled = true

[metamodel]
filename = "project.syntagmax"
